## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file 2022.Instrumentos.y.Avionica.V01.C.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_159 = Integer(159); _sage_const_30 = Integer(30); _sage_const_3 = Integer(3); _sage_const_10 = Integer(10); _sage_const_8 = Integer(8); _sage_const_300 = Integer(300); _sage_const_6 = Integer(6); _sage_const_172 = Integer(172); _sage_const_178 = Integer(178); _sage_const_0 = Integer(0); _sage_const_185 = Integer(185); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_186 = Integer(186); _sage_const_187 = Integer(187); _sage_const_4 = Integer(4); _sage_const_191 = Integer(191); _sage_const_5 = Integer(5); _sage_const_198 = Integer(198); _sage_const_7 = Integer(7); _sage_const_199 = Integer(199); _sage_const_9 = Integer(9); _sage_const_200 = Integer(200); _sage_const_310 = Integer(310); _sage_const_11 = Integer(11); _sage_const_243 = Integer(243); _sage_const_12 = Integer(12); _sage_const_1852 = Integer(1852); _sage_const_25 = Integer(25)## This file (2022.Instrumentos.y.Avionica.V01.C.sagetex.sage) was *autogenerated* from 2022.Instrumentos.y.Avionica.V01.C.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('2022.Instrumentos.y.Avionica.V01.C', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = _sage_const_159 
_st_.blockbegin()
try:
 # Ejemplos sobre ondas electromagneticas
 # 22/09/2020  SageMath
 
 
 long_onda_01 = _sage_const_30            # [m] longitud onda dato
 velocidad_luz = _sage_const_3  * _sage_const_10 **_sage_const_8    # [m/seg] velocidad de la luz en vacio
 
 frecuencia_01 = velocidad_luz / long_onda_01  # [Hz] frecuencia correspondiente a long_onda_01
 
 frecuencia_02 = _sage_const_300          # [MHz] frecuencia dato
 long_onda_02  = velocidad_luz / frecuencia_02 / _sage_const_10 **_sage_const_6  # [m] long_onda correspondiente a frecuencia_02
 
   
except:
 _st_.goboom(_sage_const_172 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_178 
 _st_.inline(_sage_const_0 , latex(round(long_onda_01,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_178 )
try:
 _st_.current_tex_line = _sage_const_185 
 _st_.inline(_sage_const_1 , latex(round(velocidad_luz,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_185 )
try:
 _st_.current_tex_line = _sage_const_185 
 _st_.inline(_sage_const_2 , latex(round(long_onda_01,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_185 )
try:
 _st_.current_tex_line = _sage_const_186 
 _st_.inline(_sage_const_3 , latex(round(frecuencia_01,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_186 )
try:
 _st_.current_tex_line = _sage_const_187 
 _st_.inline(_sage_const_4 , latex(round(frecuencia_01 / _sage_const_10 **_sage_const_6 ,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_187 )
try:
 _st_.current_tex_line = _sage_const_191 
 _st_.inline(_sage_const_5 , latex(round(frecuencia_02,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_191 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_6 , latex(round(velocidad_luz,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_198 
 _st_.inline(_sage_const_7 , latex(round(frecuencia_02,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_198 )
try:
 _st_.current_tex_line = _sage_const_199 
 _st_.inline(_sage_const_8 , latex(round(velocidad_luz,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_199 )
try:
 _st_.current_tex_line = _sage_const_199 
 _st_.inline(_sage_const_9 , latex(round(frecuencia_02 * _sage_const_10 **_sage_const_6  ,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_199 )
try:
 _st_.current_tex_line = _sage_const_200 
 _st_.inline(_sage_const_10 , latex(round(long_onda_02,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_200 )
try:
 _st_.current_tex_line = _sage_const_310 
 _st_.inline(_sage_const_11 , latex(round(_sage_const_4  * _sage_const_10 **{-_sage_const_7 } , * BackslashOperator() * protect  * BackslashOperator() * protect  * BackslashOperator() * unhbox  * BackslashOperator() * voidb@x  * BackslashOperator() * hbox {)}))
except:
 _st_.goboom(_sage_const_310 )
try:
 _st_.current_tex_line = _sage_const_243 
 _st_.inline(_sage_const_12 , latex(round(_sage_const_1852  * _sage_const_25 ,_sage_const_0 )))
except:
 _st_.goboom(_sage_const_243 )
_st_.endofdoc()

